In [1]:
print("Broad Casting")

Broad Casting


In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a + 5)

[6 7 8 9]


In [4]:
import numpy as np
b = np.array([3,8,7,9])
print(b*5)

[15 40 35 45]


In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [8]:
import numpy as np 
s = np.array([2,4,6])
print(s/2)

[1. 2. 3.]


In [9]:
import numpy as np
a = np.array([[1,2],
              [3,4]])
print(a + 10)

[[11 12]
 [13 14]]


In [16]:
import numpy as np
arr = np.array([10])
print(arr[::2])



[10]


In [17]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([1,1,1])
print(a+b)

[[2 3 4]
 [5 6 7]]


In [18]:
import numpy as np
a = np.array(["Python","Java","C","C++"])
print(a + "Language")

['PythonLanguage' 'JavaLanguage' 'CLanguage' 'C++Language']
