In [1]:
print("Concatenate")


Concatenate


In [6]:
import numpy as np
a = (["Sweety"])
b = (["Narukulla"])
c = np.concatenate((a,b))
print(c)

['Sweety' 'Narukulla']


In [7]:
import numpy as np
a = ([10,20,30,40,50])
b = ([60,70,80,90,100])
c = np.concatenate((a,b))
print(c)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
import numpy as np
a = ([10,20],[30,40]

In [2]:
print("sort")


sort


In [4]:
numbers = [1,3,5,7,9,8,6,4,2]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
names = ["Archana","Sweety","Narukulla"]
names.sort()
print(names)

['Archana', 'Narukulla', 'Sweety']


In [6]:
numbers = [3,7,4,9,5,8]
numbers.sort(reverse = True)
print(numbers)

[9, 8, 7, 5, 4, 3]


In [7]:
numbers = [1,3,5,7,9,8,6,4,2]
numbers.sort()
print("Sorted List:",numbers)

Sorted List: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
print("split")

split


In [10]:
name = "My name is Archana"
result = name.split()
print(result)

['My', 'name', 'is', 'Archana']


In [12]:
names = "Archana,Sweety,Narukulla"
result = names.split(",")
print(result)

['Archana', 'Sweety', 'Narukulla']


In [14]:
text = input("Enter names:")
names = text.split()
print(names)

Enter names: Archana,Sweety,Narukulla


['Archana,Sweety,Narukulla']


In [15]:
print("Stack")

Stack


In [17]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(np.stack((a,b)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
import numpy as np
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
print(np.vstack((a,b)))

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [19]:
import numpy as np
a = np.array([11,22,33,44,55])
b = np.array([12,23,34,45,56])
print(np.hstack((a,b)))

[11 22 33 44 55 12 23 34 45 56]
