In [2]:
import numpy as np
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [3]:
cherry = np.array([100,200,300,400])
print(cherry)

[100 200 300 400]


In [9]:
import numpy as np
sweety = [100,200,300,400,500,600]
arr = np.array(sweety)
avg = np.average(arr)
print(avg)

350.0


In [11]:
import numpy as np 
sweety = ([10,20],[20,30],[30,40],[40,50])
arr = np.array(sweety)
print(arr)

[[10 20]
 [20 30]
 [30 40]
 [40 50]]


In [15]:
a = np.array([10,20,30,40])
b = np.array([60,70,80,90])
print(a/b)
print(a+b)
print(a-b)
print(a*b)

[0.16666667 0.28571429 0.375      0.44444444]
[ 70  90 110 130]
[-50 -50 -50 -50]
[ 600 1400 2400 3600]


In [16]:
a = np.mean([10,11,12,13,14])
print(a)

12.0


In [17]:
b = np.array([11,22,33,44,55])
print(np.max(b))

55


In [18]:
c = np.array([11,22,33,44,55,66,77,88])
print(np.min(c))

11


In [19]:
d = np.array([1,2,3,4,5,6,7,8,9])
print(np.mean)

<function mean at 0x000002086AF17CE0>


In [20]:
import numpy as np
b=np.array([[1,2,3],
            [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
c=np.array(["Apple","Mango","Banana"])
print(c)

['Apple' 'Mango' 'Banana']


In [22]:
s = np.array([1.5,2.5,3.5,4.5,5.5])
print(d)

[1 2 3 4 5 6 7 8 9]


In [23]:
import numpy as np 
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[0])
print(arr[3])
print(arr[6])

10
40
70


In [3]:
import numpy as np
arr = np.array([[10,20,30],[10,20,30],
               [40,50,60],[80,30,20],
               [20,10,40],[50,34,85]])
print(arr)

[[10 20 30]
 [10 20 30]
 [40 50 60]
 [80 30 20]
 [20 10 40]
 [50 34 85]]
